USE [master]
GO

/****** Object:  Database [HarmonyClin]    Script Date: 14/11/2020 16:55:16 ******/
CREATE DATABASE [HarmonyClin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HarmonyClin', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HarmonyClin.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HarmonyClin_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HarmonyClin_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HarmonyClin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HarmonyClin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HarmonyClin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HarmonyClin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HarmonyClin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HarmonyClin] SET ARITHABORT OFF 
GO

ALTER DATABASE [HarmonyClin] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HarmonyClin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HarmonyClin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HarmonyClin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HarmonyClin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HarmonyClin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HarmonyClin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HarmonyClin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HarmonyClin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HarmonyClin] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HarmonyClin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HarmonyClin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HarmonyClin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HarmonyClin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HarmonyClin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HarmonyClin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HarmonyClin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HarmonyClin] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HarmonyClin] SET  MULTI_USER 
GO

ALTER DATABASE [HarmonyClin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HarmonyClin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HarmonyClin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HarmonyClin] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HarmonyClin] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HarmonyClin] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HarmonyClin] SET  READ_WRITE 
GO


